name: Install AIDL

on:
  push:
    branches:
      - main # Ana dalınıza göre ayarlayın

jobs:
  install-aidl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install AIDL
      run: |
        sudo apt-get update
        sudo apt-get install -y aidl
